"""Configurações da aplicação."""

from os import getenv
from dotenv import load_dotenv

load_dotenv()

POCKETBASE_URL = getenv("POCKETBASE_URL")
POCKETBASE_EMAIL = getenv("POCKETBASE_EMAIL")
POCKETBASE_PASSWORD = getenv("POCKETBASE_PASSWORD")
COLLECTION_RELEASES = getenv("COLLECTION_RELEASES")

SIMPLESVET_EMAIL = getenv("SIMPLESVET_EMAIL")
SIMPLESVET_PASSWORD = getenv("SIMPLESVET_PASSWORD")

DAYS_RANGE = int(getenv("DAYS_RANGE"))
SYNC_INTERVAL_MINUTES = int(getenv("SYNC_INTERVAL_MINUTES"))